import img from "../../assets/logo.jpg";
import o2 from "../../assets/o1.jpg";
import o1 from "../../assets/o2.jpg";
import o3 from "../../assets/o3.jpg";
import gpay from "../../assets/gpay.png";

export const appData = [
  {
    id: "1",
    categoryName: "ONLINE BETTINg games",
    appName: "Rummy perfect signup bonus Rs.51",
    icon: gpay,
    postedDate: "posted on March 4, 2023 by ",
    imgPoster: img,
    appLink: "www.youtube.com",
    installProess: "Install register , Bind mobile number get instanly Rs.51",
    rechargeImg: o2,
    rechargeVideoLink: "",
    withdrawImg: o1,
    withdrawVideoLink: "",
    installRegisterImg: o3,
    installVideoLink: "",
  },
  {
    id: "2",
    categoryName: "Fantasy games",
    appName: "Rummy perfect signup bonus Rs.51",
    icon: gpay,
    postedDate: "posted on March 4, 2023 by ",
    imgPoster: img,
    appLink: "www.youtube.com",
    installProess: "Install register , Bind mobile number get instanly Rs.51",
    rechargeImg: o2,
    rechargeVideoLink: "",
    withdrawImg: o1,
    withdrawVideoLink: "",
    installRegisterImg: o3,
    installVideoLink: "",
  },
  {
    id: "7",
    categoryName: "Fantasy games",
    appName: "Rummy perfect signup bonus Rs.51",
    icon: gpay,
    postedDate: "posted on March 4, 2023 by ",
    imgPoster: img,
    appLink: "www.youtube.com",
    installProess: "Install register , Bind mobile number get instanly Rs.51",
    rechargeImg: o2,
    rechargeVideoLink: "",
    withdrawImg: o1,
    withdrawVideoLink: "",
    installRegisterImg: o3,
    installVideoLink: "",
    hotDeal: true,
  },
  {
    id: "3",
    categoryName: "Fantasy games",
    appName: "Rummy perfect signup bonus Rs.51",
    icon: gpay,
    postedDate: "posted on March 4, 2023 by ",
    imgPoster: img,
    appLink: "www.youtube.com",
    installProess: "Install register , Bind mobile number get instanly Rs.51",
    rechargeImg: o2,
    rechargeVideoLink: "",
    withdrawImg: o1,
    withdrawVideoLink: "",
    installRegisterImg: o3,
    installVideoLink: "",
    hotDeal: true,
  },
  {
    id: "4",
    categoryName: "Fantasy games",
    appName: "Rummy perfect signup bonus Rs.51",
    icon: gpay,
    postedDate: "posted on March 4, 2023 by ",
    imgPoster: img,
    appLink: "www.youtube.com",
    installProess: "Install register , Bind mobile number get instanly Rs.51",
    rechargeImg: o2,
    rechargeVideoLink: "",
    withdrawImg: o1,
    withdrawVideoLink: "",
    installRegisterImg: o3,
    installVideoLink: "",
  },
  {
    id: "5",
    categoryName: "Fantasy games",
    appName: "Rummy perfect signup bonus Rs.51",
    icon: gpay,
    postedDate: "posted on March 4, 2023 by ",
    imgPoster: img,
    appLink: "www.youtube.com",
    installProess: "Install register , Bind mobile number get instanly Rs.51",
    rechargeImg: o2,
    rechargeVideoLink: "",
    withdrawImg: o1,
    withdrawVideoLink: "",
    installRegisterImg: o3,
    installVideoLink: "",
    hotDeal: true,
  },
];
